name: Docker Image CI

on:
  workflow_dispatch:
    
  push:
    branches: [ "master" ]


jobs:

  build:

    runs-on: ubuntu-latest
  

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kirtinagpal077/app
   
    - name: docker run 
      run: docker run -d -p8009:8000 kirtinagpal077/app
    - name: docker ps 
      run: docker ps -a
